baseURL = "https://blog.v5u.win"
languageCode = "zh-CN"
defaultContentLanguage = "en"
title = "为吾优"
subtitle = "世界很大，思想无边"
enableRobotsTXT = true
rssLimit = 10  # Maximum number of items in the RSS feed.
theme =  "minimal"
hasCJKLanguage = true
PaginatePath = "page"
paginate = 20
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
#googleAnalytics = "UA-166045776-1"

[author]
    name = "金玉游龙"

[params]
  since = "2014"
  toc = true
  dateform        = "2006-01-02"
  dateformShort   = "01-02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  author = "范金龙"
  description = "走在通往幸福的路上"
  subtitle = "走在通往幸福的路上"
  keywords = "博客,Web,Go,iOS"
  customCSS = ["style.extra.css"]
  customJS = ["app.extra.js"]
  themeColor = "#494f5c"


  [[params.social]]
    name = "github"
    url = "https://github.com/jinyuyoulong"
  [[params.social]]
    name = "About"
    url = "https://blog.v5u.win/desc/about/"

  [params.utteranc]
      repo = "JokerQyou/comments"
      issueTerm = "url"
      theme = "github-light"

  [[params.links]]
      name = "海之飞燕 博客"
      url = "https://v2it.win/"
      title = "代码如诗，人生无限。"
  [[params.links]]
      name = "为吾优导航"
      url = "https://blog.v5u.win/navigations/navigate.html"
      title = "人生迷茫，我有导航"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 4